version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI_PROD}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - my-network

  mongo:
    image: mongo:latest
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network
    healthcheck:
      test: ["CMD-SHELL", "mongo --eval 'db.adminCommand(\"ping\")'"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:

networks:
  my-network:
    driver: bridge

x-environment-variables:
  MONGO_URI: ${MONGO_URI_PROD}
  MONGO_USERNAME: ${MONGO_USERNAME}
  MONGO_PASSWORD: ${MONGO_PASSWORD}